# The resource system doesn't gen the file, so you can copy this.

token: 'Your token will be safe in this value'

mongo-ip: "127.0.0.1"
mongo-port: "27017"
mongo-auth-database: "admin"
mongo-storage-database: "giveaway-bot"
mongo-username: "yourUsername" # If you dont have credentials for ur DB, just remove the actual config parts themselves, so comment the entire username and password section.
mongo-password: "thisIsSecure"

enable-metrics: false
influx-url: 'https://your.instance.com'
influx-token: 'your-token'
influx-org: SmartGiveaways
influx-bucket: bot

# Not yet used
redis-host: 127.24.114.43
redis-port: 6379
use-redis-ssl: true
redis-password: "some-pass"

default-language: "english-uk"

latency-tester:
  file-for-lines: some-file.txt
  channel-id: 775406909216784385